name: Update package libs

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - name: Download Native Libs
      run: go run download_libs/download_libs.go
    - name: Commit and push updates
      uses: test-room-7/action-update-file@v1
      with:
        file-path: |
            libs/linux_amd64/libLexActivator.a
            libs/linux_arm64/libLexActivator.a
            libs/darwin_amd64/libLexActivator.a
            libs/windows_amd64/LexActivator.dll
        commit-msg: Updated native libs
        github-token: ${{ secrets.GITHUB_TOKEN }}